### ISSUE TITLE
If string length is lower than array size, compiler crashes

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [maviek/sapphire#3]
Code:

```
var a[7]
a = "test"
```

Output:
```
Traceback (most recent call last):
  File "main.py", line 63, in <module>
    e(m(b,a))
  File "main.py", line 47, in main
    parser = Parser(lexer)
  File "/workspace/src/_parser.py", line 11, in __init__
    self.parse()
  File "/workspace/src/_parser.py", line 64, in parse
    self.codegen('mov', 'r2', ord(token.value[i + 1]))
IndexError: string index out of range
```

**Comment by maviek** [comment]
fixed!
