### ISSUE TITLE
When passing output file, no error messages pop up.

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [maviek/sapphire#8]
Self-descriptional terminal log:

```
> python main.py -asm atoi.sph out.asm

> python main.py -asm atoi.sph
Traceback (most recent call last):
  File "main.py", line 78, in <module>
    e(m(b,a))
  File "main.py", line 62, in main
    parser = Parser(lexer, stack_size)
  File "/workspace/src/_parser.py", line 16, in __init__
    self.parse()
  File "/workspace/src/_parser.py", line 145, in parse
    c = 'mov r1,' + str(self.memory.addresses[l.split(' ')[1]]) + '\n'
KeyError: 'res'
```

**Comment by maviek** [comment]
![image](https://user-images.githubusercontent.com/29343327/47869970-9a9ec080-de08-11e8-88dc-22b21ece4107.png)
